# 1. Préliminaires

# 1.1 Contexte 
AI Worker Burnout Attrition : [Dataset](https://www.kaggle.com/datasets/nudratabbas/ai-worker-burnout-and-attrition-risk-dataset/data)


Ce dataset utilisé dans ce repository pour pratiquer l'analyse de donnée.

## 1.2 Importations des librairies

In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

## 1.3 Chargement des données

In [2]:
# chargement des données
data = pd.read_csv('./data/ai_worker_burnout_attrition_2026.csv')

# Affichage d'un extrait
data.head()

,employee_id,job_role,years_experience,education_level,country,industry,company_size,remote_work_type,team_size,salary_usd_k,...,ai_tools_used_per_day,hours_with_ai_assistance_daily,ai_replaces_my_tasks_pct,ai_adoption_stage,weekly_ai_upskilling_hrs,productivity_score,burnout_score,job_satisfaction_1_5,fear_of_ai_replacement,attrition_risk
0,EMP0001,Data Analyst,7,PhD,India,Healthtech,Large (1000-5000),Fully Remote,8,184,...,1,0.6,37,Experimenting,4.9,59,58,3.0,Low,Medium
1,EMP0002,DevOps Engineer,3,Self-taught,Canada,Fintech,Large (1000-5000),Hybrid,42,51,...,3,0.6,78,Experimenting,6.6,64,47,3.6,Medium,Medium
2,EMP0003,Prompt Engineer,3,PhD,India,Automotive,Startup (<50),Hybrid,37,185,...,4,4.0,23,Optimizing,5.8,50,37,4.6,High,Medium
3,EMP0004,Backend Engineer,18,Master,Germany,Media,Mid (200-1000),Fully Remote,8,131,...,5,4.2,75,Integrating,1.4,77,67,3.0,Low,Medium
4,EMP0005,AI Researcher,5,Bachelor,India,E-commerce,Small (50-200),Fully Remote,21,99,...,7,0.7,61,Experimenting,1.6,58,54,3.6,Medium,Medium

## 1.4 Structure et Typologie des données

In [4]:
data.shape

(1500, 21)

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   employee_id                     1500 non-null   str
 1   job_role                        1500 non-null   str
 2   years_experience                1500 non-null   int64
 3   education_level                 1500 non-null   str
 4   country                         1500 non-null   str
 5   industry                        1500 non-null   str
 6   company_size                    1500 non-null   str
 7   remote_work_type                1500 non-null   str
 8   team_size                       1500 non-null   int64
 9   salary_usd_k                    1500 non-null   int64
 10  primary_ai_tool                 1500 non-null   str
 11  ai_tools_used_per_day           1500 non-null   int64
 12  hours_with_ai_assistance_daily  1500 non-null   float64
 13  ai_replaces_my_tasks_pct        1500 non-null   int64
 14  ai_adoption_stage               1500 non-null   str
 15  weekly_ai_upskilling_hrs        1500 non-null   float64
 16  productivity_score              1500 non-null   int64
 17  burnout_score                   1500 non-null   int64
 18  job_satisfaction_1_5            1500 non-null   float64
 19  fear_of_ai_replacement          1500 non-null   str
 20  attrition_risk                  1500 non-null   str
dtypes: float64(3), int64(7), str(11)
memory usage: 246.2 KB

In [10]:
# selections des colonnes categorielles
categorical_cols = [
    "attrition_risk",
    "fear_of_ai_replacement",
    "ai_adoption_stage",
    "ai_tools_used_per_day",
    "primary_ai_tool",
    "education_level",
    "country",
    "industry",
    "company_size",
    "remote_work_type"
]

# changement du type en categorie
data[categorical_cols]= data[categorical_cols].astype('category')

In [8]:
data.nunique()

employee_id                       1500
job_role                            12
years_experience                    19
education_level                      5
country                             10
industry                            10
company_size                         5
remote_work_type                     3
team_size                           48
salary_usd_k                       210
primary_ai_tool                      8
ai_tools_used_per_day                7
hours_with_ai_assistance_daily      76
ai_replaces_my_tasks_pct            75
ai_adoption_stage                    4
weekly_ai_upskilling_hrs           101
productivity_score                  62
burnout_score                       66
job_satisfaction_1_5                37
fear_of_ai_replacement               3
attrition_risk                       3
dtype: int64

## 1.5 Choix des colonnes quantitatives

In [11]:
features = [
    "years_experience",
    "team_size",
    "salary_usd_k",
    "ai_tools_used_per_day",
    "hours_with_ai_assistance_daily",
    "ai_replaces_my_tasks_pct",
    "weekly_ai_upskilling_hrs",
    "burnout_score",
    "productivity_score",
]
df = data[features]
df.head()

,years_experience,team_size,salary_usd_k,ai_tools_used_per_day,hours_with_ai_assistance_daily,ai_replaces_my_tasks_pct,weekly_ai_upskilling_hrs,burnout_score,productivity_score
0,7,8,184,1,0.6,37,4.9,58,59
1,3,42,51,3,0.6,78,6.6,47,64
2,3,37,185,4,4.0,23,5.8,37,50
3,18,8,131,5,4.2,75,1.4,67,77
4,5,21,99,7,0.7,61,1.6,54,58